# Display
name: CustomCommands
description: 'The easiest, and most feature packed custom commands plugin !'
author: PYRRH4
website: www.pyrrh4.be
# Techy
version: 3.1.0
api-version: 1.13
main: be.pyrrh4.customcommands.CustomCommands
depend: [PyrCore]
# Commands
commands:
  customcommands:
    description: Custom commands
    aliases: [ccmd]
# Permission
permissions:
  customcommands.admin:
    default: op
